# Generated by Django 3.1.1 on 2020-09-19 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20200919_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='default_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.photo'),
        ),
    ]
