# Generated by Django 3.1.1 on 2020-09-19 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_auto_20200919_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='default_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.photo'),
        ),
    ]
