# Generated by Django 3.1.1 on 2020-09-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_auto_20200920_0304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'ordering': ['created']},
        ),
    ]
