# Generated by Django 3.1.1 on 2020-09-20 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_auto_20200920_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.summary'),
        ),
    ]
