# Generated by Django 3.1.1 on 2020-09-20 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_photo_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.summary'),
        ),
    ]
