# Generated by Django 3.1.1 on 2020-09-20 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0017_auto_20200920_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='albums_in',
            field=models.ManyToManyField(blank=True, to='gallery.Album'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
