# Generated by Django 3.1.1 on 2020-09-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0019_auto_20200920_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
