# Generated by Django 3.1.1 on 2020-09-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0020_auto_20200920_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
