# Generated by Django 3.1.1 on 2020-09-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0021_auto_20200920_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='comments',
        ),
    ]
